---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sxc.
--- DateTime: 2022/10/20 8:43
---
if (redis.call('GET',KEYS[1])==ARGV[1]) then
    return redis.call('DEL',KEYS[1])
end
return 0
